name: eo_color
description: An elegant collection of color related classes and interfaces as an alternative to the Flutter's built-in colors, as well as an object-oriented implementation of the Material Design color palettes.
version: 0.0.1
homepage: https://dartoos.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
